version: 2.1

executors:
  cci-clojure:
    docker:
      - image: cimg/clojure

# TODO: Add ways to save build cache

jobs:
  build-image:
    working_directory: ~/project
    executor: cci-clojure
    steps:
      - checkout
      - restore_cache:
         keys:
           - m2-{{ checksum "project.clj" }}
           - m2-
      - run:
          name: lein deps
          command: lein deps
      - save_cache:
          key: m2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Lein build uberjar
          command: lein uberjar
      - run:
          name: Docker Build
          command: |
            docker build . \
              --tag success \
              --tag registry.digitalocean.com/obax/success:latest
      - run: &docker-login
          name: Docker Login
          command: |
            docker login registry.digitalocean.com \
              --password $DOCKER_REGISTRY_TOKEN \
              --username $DOCKER_REGISTRY_TOKEN
      - run:
          name: Docker Push
          command: docker image push registry.digitalocean.com/obax/success:latest
      # - run:
      #     name: Docker Run
      #     command: docker run success

  pull_image:
    machine: true
    steps:
      - run:
          <<: *docker-login
      - run:
          name: Image pull
          command: docker pull registry.digitalocean.com/obax/success:latest

workflows:
  build-deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only: main
          # requires:
          #   - build-jar
            # tags:
            #   only: \d*
      - pull_image:
          requires:
            - build-image
