version: 2.1

# TODO: Add ways to save build cache

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Build
          command: |
            docker build . \
              --tag success \
              --tag registry.digitalocean.com/obax/success:latest
      - run: &docker-login
          name: Docker Login
          command: |
            docker login registry.digitalocean.com \
              --password $DOCKER_REGISTRY_TOKEN \
              --username $DOCKER_REGISTRY_TOKEN
      - run:
          name: Docker Push
          command: docker image push registry.digitalocean.com/obax/success:latest
      - run:
          name: Docker Run
          command: docker run success

  pull_image:
    machine: true
    steps:
      - run:
          <<: *docker-login
      - run:
          name: Image pull
          command: docker pull registry.digitalocean.com/obax/success:latest

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
            tags:
              only: "*"
      - pull_image:
          requires:
            - build
