version: 2.1

# TODO: Add ways to save build cache

executors:
  cci-clojure:
    docker:
      - image: cimg/clojure:1.10.1

environment:
  DOCKER_REGISTRY_HOST: registry.digitalocean.com
  DOCKER_REGISTRY_USER: obax

jobs:
  build-image:
    working_directory: ~/project/app
    executor: cci-clojure
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - restore_cache:
         keys:
           - m2-{{ checksum "project.clj" }}
           - m2-
      - run:
          name: lein deps
          command: lein deps
      - save_cache:
          key: m2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Lein build uberjar
          command: lein uberjar
      - run:
          name: Docker Build
          command: |
            docker build . \
              --tag $DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:latest \
              --tag $DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM \
      - run: &docker-login
          name: Docker Login
          command: |
            docker login registry.digitalocean.com \
              --password $DOCKER_REGISTRY_TOKEN \
              --username $DOCKER_REGISTRY_TOKEN

      # The fallback exists only because older versions of push command do not accept --all-tags
      - run:
          name: Docker Push
          command: |
            docker image push --all-tags $DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:latest ; \
            docker image push $DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:latest

  pull-image:
    machine: true
    steps:
      - run:
          <<: *docker-login
      - run:
          name: Image pull
          command: docker pull $DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USER/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  build-deploy:
    jobs:
      - build-image:
          filters:
            branches:
              only: main
          # requires:
          #   - build-jar
            # tags:
            #   only: \d*
      - pull-image:
          requires:
            - build-image
